name: Mkoenov
favicon: null
layout_spectrum: 0.3028836401645094
typography_spectrum: 0.4568436301779002
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7917642856482416
  lightness: 0.018260242650285363
  saturation: 0.6941061594989151
  rhythmicContrast: 0.14448802848346531
purpose: []
