name: Mkoenov
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6171
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e8a98'
    - '#0b0b17'
    - '#0a4b9b'
    - '#95e0ff'
    - '#ffe35b'
  brandStrength: 0.9375
  lightness: 0.0625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
